language: node_js

stages:
  - lint
  - test
  - compile

node_js:
  - "12"

cache: npm

jobs:
  include:
    # ESLint
    - stage: "lint"
      name: "ESLint"
      install:
        - npm install
      script:
        - npm run lint
    # Unit Test
    - stage: "test"
      name: "Unit Test"
      script:
        - npm run test:unit
    # Build Compile
    - stage: "compile"
      name: "Build Compile"
      before_install:
        - if [[ $TRAVIS_NODE_VERSION == 8 ]]; then npm i -g npm@latest; fi
      install:
        - rm -rf node_modules && npm install
      script:
        - npm run build --spa
