language: node_js

stages:
  - lint
  - test
  - compile

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "lint"
      name: "ESLint"
      install:
        - |
          npm install eslint \
          eslint-plugin-vue \
          @typescript-eslint/parser \
          @typescript-eslint/typescript-estree
      script:
        - node_modules/eslint/bin/eslint.js .
    - stage: "test"
      name: "Unit Test"
      script:
        - npm run test:unit
    - stage: "compile"
      name: "Build Compile"
      install:
        - npm install
      script:
        - npm run build --spa
