# yarn build
# gcloud app deploy app.yaml --project nuxt-admin-web

runtime: nodejs

env: flex

# 256MB
instance_class: F2

automatic_scaling:
  min_instances: 0

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    # HTTPS
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    # HTTPS
    secure: always

  - url: /sw.js
    static_files: static/sw.js
    upload: static/sw.js
    # HTTPS
    secure: always

  - url: /.*
    script: auto
    # HTTPS
    secure: always

env_variables:
  NUXT_HOST: 0.0.0.0
  NUXT_PORT: 8080
  NODE_ENV: 'production'
  API_KEY: 'AIzaSyAV7kCXzIPqtKeFnaNz-ywA3NEBUBw7S24'
  AUTH_DOMAIN: 'nuxtadmin-4a9e0.firebaseapp.com'
  PROJECT_ID: 'nuxt-admin-tokyo'
  GRAPH_API: 'https://api.graph.cool/simple/v1/cjr94yoay4hds0196reyj9lke'
  APOLLO_KEY: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDgyNDQ3NzQsImNsaWVudElkIjoiY2pyOTR5b2F5NGhkdDAxOTYwajIwdDE1aiJ9.WulBc4uocM_ytX6b6-U9Et_ieGGERE2BpYZVkpaBUlo'
