version: '3'
services:
  admin_front:
    container_name: admin_front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/src:cached
      # exclude volumes
      - /client/node_modules
    tty: true
    stdin_open: true
    env_file: ./.env
    environment:
      # enabled HMR
      - CHOKIDAR_USEPOLLING=true
  admin_api:
    container_name: admin_api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
