[build]

# Admin 本番環境
[context.production]
  command = "npm run generate"
  publish = "dist"
  environment = { API_KEY = "AIzaSyAV7kCXzIPqtKeFnaNz-ywA3NEBUBw7S24", AUTH_DOMAIN = "nuxtadmin-4a9e0.firebaseapp.com", PROJECT_ID = "nuxt-admin-tokyo" }

# Storybook 開発環境
[context.storydev]
  command = "npm run build-storybook"
  publish = "storybook-static"
