name: Functions CI

on:
  schedule:
    - cron: "5 3 * * 3"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy
        run: |
          npm install -g firebase-tools
          cd functions
          npm install --arch=x64 --platform=linuxmusl
          firebase deploy --token $FIREBASE_TOKEN
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "nuxt-admin-tokyo"
